print("====GENIE FANTASY STORY GENERATOR====")
print("")
print("")
print("")
print("")
BoysName = input("What is the name of the main character? ")
ObjectGenie = input("What is the object that the genie is trapped in? ")
GenieName = input("What is the name of the genie? ")
FirstWish = input("What is the first wish? ")
SecondWish = input("What is the second wish? ")
ThirdWish = input("What is the third wish? ")
VillainName = input("What is the name of the villain? ")
VillainPower = input("What is the power of the villain? ")
AlteriorMotive = input("What is the alterior motive of the villain? ")
SidekickName = input("What is the name of the hero's sidekick? ")

print("")
print("")
print("")
print("")
print("Once upon a time, in a far away land", BoysName, "found a", ObjectGenie, "and released", GenieName, "from it. In return for freeing him, the")
print(GenieName, "granted", BoysName, "three wishes. The first wish was", FirstWish, "and the second wish was", SecondWish, "and the third wish was", ThirdWish, ".")
print("However, watching from the shadows was the evil", VillainName, "who had the power of", VillainPower, "and an alterior motive to take over the kingdom.")
print("With the help of his trusty sidekick", SidekickName, ",", BoysName, "defeated", VillainName, "and saved the kingdom.")   
print("")
print("THE END")


